name: ci

on: push

env:
  SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
  SERVER_SECRET: ${{ secrets.SERVER_SECRET }}
  MONGODB_URI: ${{ secrets.MONGODB_URI }}

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Run test
        run: npm test
  cd:
    runs-on: ubuntu-latest
    needs: ci
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.SSH_HOST}}
          username: ${{ secrets.SSH_USERNAME}}
          port: ${{ secrets.SSH_PORT}}
          password: ${{ secrets.SSH_PASSWORD}}
          script: |
            cd ~/se2/11/
            git clone https://${{ secrets.CLONE_TOKEN }}@github.com/SoftwareEngineering2-Assignment/se2-backend-group-11
            cd se2-backend-group-11
            npm install
            pm2 restart se2-backend-group-11 --update-env
    